FROM ghcr.io/kurrawong/fuseki:5.6.0-0

ARG FUSEKI_HOME=/opt/fuseki
ARG FUSEKI_BASE=/fuseki

USER root

RUN mkdir -p "${FUSEKI_HOME}/configuration"
COPY config.ttl "${FUSEKI_HOME}/configuration/ds.ttl"

ADD https://github.com/Kurrawong/jena-compound-naming/releases/download/1.0.0/compoundnaming-1.0.0.jar "${FUSEKI_HOME}/lib/compoundnaming.jar"

RUN chown fuseki:fuseki "${FUSEKI_HOME}/configuration/ds.ttl" "${FUSEKI_HOME}/lib/compoundnaming.jar" && \
    chmod 0644 "${FUSEKI_HOME}/configuration/ds.ttl" "${FUSEKI_HOME}/lib/compoundnaming.jar"

USER fuseki
