db_connection: postgresql://postgres:postgres@localhost:5432/address

tables:
  - lalfdb.lalfpdba_lf_parcel
  - lalfdb.lalfpdba_lf_address # ~129min
  - lalfdb.lalfpdba_lf_geocode # ~6min
  - lalfdb.lalfpdba_sp_survey_point # ~3min
  - lalfdb.lalfpdba_lf_status # ~3sec
  - lalfdb.locality # ~4sec
  - lalfdb.qrt # ~17min
  - lalfdb.lalfpdba_lf_address_history # ~32min
  - lalfdb.lapnpdba_placenm # ~16sec
  - lalfdb.lalfpdba_lf_place_name # ~50sec
  - lalfdb.lalfpdba_lf_unit_type
  - lalfdb.lalfpdba_lf_level_type

# Value is a SQL list
site_ids: "(1066374, 1075435, 2578313, 1724075, 33254, 1837741)"
