import argparse
import csv
import time
from pathlib import Path
from textwrap import dedent

from cam.etl import get_db_connection
from cam.etl.lalf_address import get_address_iri
from cam.etl.settings import settings


DEFAULT_OUTPUT = Path("lf_address_addr_id_to_iri.csv")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Export lf_address addr_id values and the address IRIs generated by "
            "etl_lalf_address.py."
        )
    )
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"CSV output path. Defaults to {DEFAULT_OUTPUT}.",
    )
    parser.add_argument(
        "--include-historic",
        action="store_true",
        help="Include historic addresses. By default, addr_status_code = 'H' is excluded.",
    )
    return parser.parse_args()


def write_address_iri_dump(output_path: Path, include_historic: bool) -> int:
    output_path.parent.mkdir(parents=True, exist_ok=True)

    where_clause = "" if include_historic else "WHERE addr_status_code != 'H'"
    row_count = 0

    with get_db_connection(
        host=settings.etl.db.host,
        port=settings.etl.db.port,
        dbname=settings.etl.db.name,
        user=settings.etl.db.user,
        password=settings.etl.db.password,
    ) as connection:
        with connection.cursor(name="main", scrollable=False) as cursor:
            cursor.itersize = settings.etl.batch_size
            cursor.execute(
                dedent(
                    f"""\
                    SELECT addr_id
                    FROM "lalfpdba.lf_address"
                    {where_clause}
                    ORDER BY addr_id
                    """
                )
            )

            with output_path.open("w", newline="", encoding="utf-8") as csv_file:
                writer = csv.writer(csv_file)
                writer.writerow(["addr_id", "address_iri"])

                while True:
                    rows = cursor.fetchmany(settings.etl.batch_size)
                    if not rows:
                        break

                    for row in rows:
                        addr_id = row["addr_id"]
                        writer.writerow([addr_id, get_address_iri(addr_id)])
                        row_count += 1

    return row_count


def main() -> None:
    args = parse_args()
    start_time = time.time()

    row_count = write_address_iri_dump(args.output, args.include_historic)

    execution_time = time.time() - start_time
    print(f"Wrote {row_count} rows to {args.output}")
    print(f"Total execution time: {execution_time:.2f} seconds")


if __name__ == "__main__":
    main()
